{
  "openapi": "3.0.1",
  "info": {
    "title": "AngularCBFBackEND",
    "version": "1.0"
  },
  "paths": {
    "/api/Identity/Login": {
      "post": {
        "tags": [
          "Identity"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityLoginModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityLoginModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityLoginModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Identity/Registrar": {
      "post": {
        "tags": [
          "Identity"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityRegistroModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityRegistroModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/IdentityRegistroModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/PainelAdmin/criar-excel-jogos-cbf/{tipo}/{serie}": {
      "get": {
        "tags": [
          "PainelAdmin"
        ],
        "parameters": [
          {
            "name": "tipo",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "serie",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/PainelAdmin/importar-jogos-cbf": {
      "post": {
        "tags": [
          "PainelAdmin"
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "cbfInfo": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              },
              "encoding": {
                "cbfInfo": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Tabelas/tabela-principal/{ano}/{serie}": {
      "get": {
        "tags": [
          "Tabelas"
        ],
        "parameters": [
          {
            "name": "ano",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "serie",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Tabelas/tabela-jogos-recentes": {
      "get": {
        "tags": [
          "Tabelas"
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "IdentityLoginModel": {
        "required": [
          "password",
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "IdentityRegistroModel": {
        "required": [
          "email",
          "funcao",
          "password",
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          },
          "funcao": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      }
    }
  }
}